// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoPrDy4c4GKbXPcWDX6opRePo1JtZdhY8',
    appId: '1:613148055539:web:bff71d6ae0922e0795a486',
    messagingSenderId: '613148055539',
    projectId: 'workconnect-65a88',
    authDomain: 'workconnect-65a88.firebaseapp.com',
    storageBucket: 'workconnect-65a88.firebasestorage.app',
    measurementId: 'G-C9W9ZY2XTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKvI4qGwTWXRFJelUAP4egT-ZhzjwGyr0',
    appId: '1:613148055539:android:901e4a2d976e358f95a486',
    messagingSenderId: '613148055539',
    projectId: 'workconnect-65a88',
    storageBucket: 'workconnect-65a88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCktpnneUv7FkL5tNFkIpX-_4hOFIO7dI',
    appId: '1:613148055539:ios:25a9272ce241c89395a486',
    messagingSenderId: '613148055539',
    projectId: 'workconnect-65a88',
    storageBucket: 'workconnect-65a88.firebasestorage.app',
    iosBundleId: 'com.example.workconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCktpnneUv7FkL5tNFkIpX-_4hOFIO7dI',
    appId: '1:613148055539:ios:25a9272ce241c89395a486',
    messagingSenderId: '613148055539',
    projectId: 'workconnect-65a88',
    storageBucket: 'workconnect-65a88.firebasestorage.app',
    iosBundleId: 'com.example.workconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoPrDy4c4GKbXPcWDX6opRePo1JtZdhY8',
    appId: '1:613148055539:web:d1607ea8c9eb87b395a486',
    messagingSenderId: '613148055539',
    projectId: 'workconnect-65a88',
    authDomain: 'workconnect-65a88.firebaseapp.com',
    storageBucket: 'workconnect-65a88.firebasestorage.app',
    measurementId: 'G-62GJYYK96W',
  );
}
